name: Deploy ASP.NET App to AKS

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'k8s/**'

env:
  ACR_NAME: ${{ secrets.ACR_LOGIN_SERVER }}    # e.g. myregistry.azurecr.io
  RESOURCE_GROUP: rg-subnetcalc                # your RG name
  CLUSTER_NAME: aks-subnetcalc                 # your AKS cluster name
  NAMESPACE: default                           # Kubernetes namespace

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Build and Publish
        working-directory: src/YourWebApp
        run: |
          dotnet restore
          dotnet publish -c Release -o publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id:     ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:     ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build & Push Docker Image
        run: |
          IMAGE_TAG=$ACR_NAME/yourwebapp:${{ github.sha }}
          docker build -t $IMAGE_TAG src/YourWebApp
          docker push $IMAGE_TAG
        env:
          DOCKER_BUILDKIT: 1

      - name: Get AKS Credentials
        run: |
          az aks get-credentials \
            --resource-group $RESOURCE_GROUP \
            --name $CLUSTER_NAME \
            --overwrite-existing

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Deploy to AKS
        run: |
          kubectl apply -f k8s/deployment.yaml --namespace $NAMESPACE
          kubectl apply -f k8s/service.yaml    --namespace $NAMESPACE
