name: Deploy ASP.NET App to AKS

on:
  workflow_dispatch: {}


env:
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}  # e.g. myregistry.azurecr.io
  RESOURCE_GROUP:    rg-subnetcalc                  # your RG name
  AKS_NAME:          aks-subnetcalc                 # your AKS cluster name
  NAMESPACE:         default                        # Kubernetes namespace

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4                     # clones your repo :contentReference[oaicite:5]{index=5}

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4                 # installs .NET for CI :contentReference[oaicite:6]{index=6}
        with:
          dotnet-version: '9.0.x'

      - name: Build & publish project
        working-directory: SubnetCalcWeb              # point at your project folder
        run: |
          dotnet restore
          dotnet publish -c Release -o publish

      - name: Login to Azure
        uses: azure/login@v2                          # authenticate to Azure :contentReference[oaicite:7]{index=7}
        with:
          client-id:       ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:       ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build & push Docker image
        run: |
          IMAGE_TAG=${{ env.ACR_LOGIN_SERVER }}/myaspapp:${{ github.sha }}
          docker build -t $IMAGE_TAG SubnetCalcWeb     # context = your project folder
          docker push $IMAGE_TAG

      - name: Get AKS credentials
        run: |
          az aks get-credentials \
            --resource-group $RESOURCE_GROUP \
            --name $AKS_NAME \
            --overwrite-existing                   # fetch kubeconfig :contentReference[oaicite:8]{index=8}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3                # installs kubectl

      - name: Deploy to AKS
        run: |
          kubectl apply -f k8s/deployment.yaml \
            --namespace $NAMESPACE                  # adjust path if your manifests live elsewhere
          kubectl apply -f k8s/service.yaml \
            --namespace $NAMESPACE
